import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :showcase, ShowcaseWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is terminated at Railway's edge proxy — by the time a request reaches
# the container it's plain HTTP, and Railway's internal healthcheck never
# sets X-Forwarded-Proto, so Plug.SSL.force_ssl returns a 301 on every
# healthcheck → deploy never goes live. Public traffic can only reach the
# app through Railway's HTTPS-only edge anyway, so force_ssl inside the
# container is redundant security with a breaking side effect.
# (If you ever run this outside a TLS-terminating proxy, re-enable below.)
#
# config :showcase, ShowcaseWeb.Endpoint,
#   force_ssl: [
#     rewrite_on: [:x_forwarded_proto],
#     exclude: [
#       hosts: ["localhost", "127.0.0.1"]
#     ]
#   ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
