defmodule Showcase.Repo.Migrations.CreateAuditLogs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:common_audit_logs, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :demo, :text, null: false
      add :entity_type, :text, null: false
      add :entity_id, :text, null: false
      add :event, :text, null: false
      add :payload, :map, default: %{}
      add :actor, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:common_audit_logs)
  end
end
