defmodule Showcase.Repo.Migrations.CreateSystemPrompts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:common_system_prompts, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :demo, :text, null: false
      add :section, :text, null: false
      add :version, :bigint, null: false, default: 1
      add :body, :text, null: false
      add :note, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:common_system_prompts, [:demo, :section, :version],
             name: "common_system_prompts_unique_demo_section_version_index"
           )
  end

  def down do
    drop_if_exists unique_index(:common_system_prompts, [:demo, :section, :version],
                     name: "common_system_prompts_unique_demo_section_version_index"
                   )

    drop table(:common_system_prompts)
  end
end
